"""
R KIDS Ministry Management System - Flask Backend API
Clean and simple API structure with Supabase integration
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
from datetime import datetime, timedelta
import os
import secrets
from functools import wraps
from config import Config

app = Flask(__name__)
# Allow all origins for CORS (http and https)
# Note: When using wildcard origins, credentials cannot be used
CORS(app, 
     resources={r"/api/*": {
         "origins": "*",
         "methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
         "allow_headers": ["Content-Type", "Authorization"]
     }})

# Load configuration
app.config.from_object(Config)

# Try to initialize Supabase/PostgreSQL database (optional - will fallback if not available)
try:
    from database import db, init_db
    from models import User, Church, Group, Guardian, Child
    init_db(app)
    print("✅ Database initialized")
except Exception as e:
    print(f"⚠️ Database initialization skipped: {e}")
    print("Using in-memory storage for development")

# Fallback in-memory storage (for development/testing)
users_db = {}
children_db = {}
parents_db = {}
guardians_db = {}
attendance_db = {}
notifications_db = {}
mfa_codes_db = {}  # Store temporary MFA codes: {token: {'code': '123456', 'expires_at': datetime}}

# Seed default admin users
def seed_admin_users():
    """Create default admin user for development"""
    admin_email = 'admin@rkids.church'
    admin_password = 'password123'
    
    # Store admin user in in-memory database
    admin_token = f"token_{admin_email}_{datetime.now().timestamp()}"
    users_db[admin_token] = {
        'id': 'admin_1',
        'email': admin_email,
        'role': 'admin',
        'name': 'Admin User'
    }
    
    print("\n✅ Admin user created:")
    print(f"   📧 Email: {admin_email}")
    print(f"   🔑 Password: {admin_password}")
    print("   ⚠️  OTP code will be generated by backend on login\n")

# Seed admin user on startup
seed_admin_users()

# Helper: Get auth token from header
def get_token():
    auth_header = request.headers.get('Authorization', '')
    if auth_header.startswith('Bearer '):
        return auth_header.split(' ')[1]
    return None

# Helper: Verify token (simplified for development)
def verify_token(token):
    # In production, verify JWT token
    return token and token in users_db

# Decorator: Require authentication
def require_auth(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        token = get_token()
        if not token or not verify_token(token):
            return jsonify({'error': 'Unauthorized'}), 401
        return f(*args, **kwargs)
    return decorated_function

# ============================================================================
# AUTHENTICATION ENDPOINTS
# ============================================================================

@app.route('/api/auth/login', methods=['POST'])
def login():
    """Login endpoint"""
    data = request.get_json()
    email = data.get('email', '').lower()
    password = data.get('password', '')
    
    # Simple validation (replace with database check)
    if email and password == 'password123':
        # Generate token (simplified)
        token = f"token_{email}_{datetime.now().timestamp()}"
        
        # Extract role from email (admin@, teacher@, parent@, teen@)
        role_map = {
            'admin': 'admin',
            'teacher': 'teacher',
            'parent': 'parent',
            'teen': 'teen'
        }
        role = 'parent'  # default
        for key, value in role_map.items():
            if email.startswith(key + '@'):
                role = value
                break
        
        user = {
            'id': email.split('@')[0] + '_id',
            'email': email,
            'role': role,
            'name': email.split('@')[0].title() + ' User'
        }
        users_db[token] = user
        
        # Generate 6-digit OTP code
        otp_code = ''.join([str(secrets.randbelow(10)) for _ in range(6)])
        expires_at = datetime.now() + timedelta(minutes=10)  # OTP expires in 10 minutes
        
        # Store OTP code with expiration
        mfa_codes_db[token] = {
            'code': otp_code,
            'expires_at': expires_at
        }
        
        print(f"🔐 Generated OTP for {email}: {otp_code} (expires at {expires_at.strftime('%H:%M:%S')})")
        
        return jsonify({
            'data': {
                'token': token,
                'requiresMFA': True,
                'otpCode': otp_code  # Send OTP to frontend (in production, send via SMS/Email)
            }
        })
    
    return jsonify({'error': 'Invalid credentials'}), 401

@app.route('/api/auth/verify-mfa', methods=['POST'])
def verify_mfa():
    """Verify MFA code"""
    data = request.get_json()
    code = data.get('code', '')
    token = data.get('token')
    
    # Get token from Authorization header if not in body
    if not token:
        auth_header = request.headers.get('Authorization', '')
        if auth_header.startswith('Bearer '):
            token = auth_header.split(' ')[1]
    
    # Verify token exists
    if not token or token not in users_db:
        return jsonify({'error': 'Invalid or expired session'}), 401
    
    # Check if OTP code exists for this token
    if token not in mfa_codes_db:
        return jsonify({'error': 'MFA code expired. Please login again.'}), 401
    
    mfa_data = mfa_codes_db[token]
    
    # Check if OTP expired
    if datetime.now() > mfa_data['expires_at']:
        del mfa_codes_db[token]
        return jsonify({'error': 'MFA code expired. Please login again.'}), 401
    
    # Verify OTP code
    if code == mfa_data['code']:
        user = users_db[token]
        # Clean up OTP code after successful verification
        del mfa_codes_db[token]
        
        return jsonify({
            'data': {
                'token': token,
                'user': user
            }
        })
    
    return jsonify({'error': 'Invalid verification code'}), 401

@app.route('/api/auth/logout', methods=['POST'])
@require_auth
def logout():
    """Logout endpoint"""
    token = get_token()
    if token in users_db:
        del users_db[token]
    return jsonify({'data': {'success': True}})

# ============================================================================
# PARENTS ENDPOINTS
# ============================================================================

@app.route('/api/parents', methods=['GET'])
@require_auth
def list_parents():
    """List all parents"""
    return jsonify({'data': list(parents_db.values())})

@app.route('/api/parents', methods=['POST'])
@require_auth
def create_parent():
    """Create new parent"""
    data = request.get_json()
    parent_id = f"parent_{len(parents_db) + 1}"
    parent = {
        'id': parent_id,
        'name': data.get('name', ''),
        'email': data.get('email', ''),
        'childrenCount': 0,
        'status': 'active'
    }
    parents_db[parent_id] = parent
    return jsonify({'data': parent}), 201

@app.route('/api/parents/<parent_id>', methods=['GET'])
@require_auth
def get_parent(parent_id):
    """Get parent by ID"""
    if parent_id in parents_db:
        return jsonify({'data': parents_db[parent_id]})
    return jsonify({'error': 'Parent not found'}), 404

# ============================================================================
# CHILDREN ENDPOINTS
# ============================================================================

@app.route('/api/children', methods=['GET'])
@require_auth
def list_children():
    """List children with optional filters"""
    parent_id = request.args.get('parent_id')
    group = request.args.get('group')
    
    children = list(children_db.values())
    
    if parent_id:
        children = [c for c in children if c.get('parentId') == parent_id]
    if group:
        children = [c for c in children if c.get('group') == group]
    
    return jsonify({'data': children})

@app.route('/api/children', methods=['POST'])
@require_auth
def create_child():
    """Create new child (pending approval)"""
    data = request.get_json()
    child_id = f"child_{len(children_db) + 1}"
    child = {
        'id': child_id,
        'registrationId': '',
        'name': data.get('name', ''),
        'age': data.get('age', 0),
        'dateOfBirth': data.get('dateOfBirth', ''),
        'group': data.get('group', ''),
        'parentId': data.get('parentId', ''),
        'status': 'pending',
        'gender': data.get('gender', ''),
        'guardians': [],
        'submittedBy': 'parent',
        'submittedAt': datetime.now().isoformat()
    }
    children_db[child_id] = child
    return jsonify({'data': child}), 201

@app.route('/api/children/pending', methods=['GET'])
@require_auth
def get_pending_children():
    """Get pending children for approval"""
    pending = [c for c in children_db.values() if c.get('status') == 'pending']
    return jsonify({'data': pending})

@app.route('/api/children/<child_id>/approve', methods=['POST'])
@require_auth
def approve_child(child_id):
    """Approve child"""
    if child_id in children_db:
        child = children_db[child_id]
        child['status'] = 'active'
        child['registrationId'] = f"RS{child['parentId'].split('_')[1] if '_' in child['parentId'] else '000'}/{len([c for c in children_db.values() if c.get('parentId') == child['parentId']])}"
        return jsonify({'data': child})
    return jsonify({'error': 'Child not found'}), 404

@app.route('/api/children/<child_id>/reject', methods=['POST'])
@require_auth
def reject_child(child_id):
    """Reject child"""
    data = request.get_json()
    if child_id in children_db:
        child = children_db[child_id]
        child['status'] = 'rejected'
        child['rejectionReason'] = data.get('reason', '')
        return jsonify({'data': child})
    return jsonify({'error': 'Child not found'}), 404

# ============================================================================
# CHECK-IN ENDPOINTS
# ============================================================================

@app.route('/api/checkin/generate-qr', methods=['POST'])
@require_auth
def generate_checkin_qr():
    """Generate check-in QR code"""
    data = request.get_json()
    child_id = data.get('child_id')
    
    qr_data = {
        'type': 'checkin',
        'child_id': child_id,
        'timestamp': datetime.now().isoformat(),
        'expires_at': (datetime.now() + timedelta(minutes=15)).isoformat()
    }
    
    import json
    qr_code = json.dumps(qr_data)
    
    return jsonify({
        'data': {
            'qr_code': qr_code,
            'expires_at': qr_data['expires_at']
        }
    })

@app.route('/api/checkin/scan-qr', methods=['POST'])
@require_auth
def scan_checkin_qr():
    """Scan and process QR code for check-in"""
    data = request.get_json()
    qr_data = data.get('qr_data')
    
    import json
    try:
        qr_info = json.loads(qr_data)
        child_id = qr_info.get('child_id')
        
        if child_id in children_db:
            child = children_db[child_id]
            return jsonify({
                'data': {
                    'child': child,
                    'guardians': child.get('guardians', [])
                }
            })
    except:
        pass
    
    return jsonify({'error': 'Invalid QR code'}), 400

# ============================================================================
# CHECK-OUT ENDPOINTS
# ============================================================================

@app.route('/api/checkout/notify/<child_id>', methods=['POST'])
@require_auth
def send_pickup_notification(child_id):
    """Send pickup notification"""
    if child_id in children_db:
        import secrets
        otp = ''.join([str(secrets.randbelow(10)) for _ in range(6)])
        
        notification = {
            'id': f"notif_{len(notifications_db) + 1}",
            'type': 'pickup',
            'title': 'Child Ready for Pickup',
            'message': f"{children_db[child_id]['name']} is ready to be picked up",
            'read': False,
            'createdAt': datetime.now().isoformat(),
            'metadata': {'child_id': child_id, 'otp': otp}
        }
        notifications_db[notification['id']] = notification
        
        return jsonify({
            'data': {
                'teacher_qr': f"pickup_{child_id}",
                'parent_qr': f"pickup_{child_id}_parent",
                'otp': otp,
                'expires_at': (datetime.now() + timedelta(minutes=30)).isoformat()
            }
        })
    return jsonify({'error': 'Child not found'}), 404

# ============================================================================
# NOTIFICATIONS ENDPOINTS
# ============================================================================

@app.route('/api/notifications', methods=['GET'])
@require_auth
def list_notifications():
    """List notifications"""
    return jsonify({'data': list(notifications_db.values())})

@app.route('/api/notifications/unread-count', methods=['GET'])
@require_auth
def get_unread_count():
    """Get unread notification count"""
    unread = len([n for n in notifications_db.values() if not n.get('read', False)])
    return jsonify({'data': {'count': unread}})

# ============================================================================
# GROUPS ENDPOINTS
# ============================================================================

@app.route('/api/groups', methods=['GET'])
@require_auth
def list_groups():
    """List all groups"""
    from utils.db_helpers import get_groups
    
    try:
        # Try to get groups from Supabase
        groups = get_groups()
        if groups:
            group_names = [g.name for g in groups]
            return jsonify({'data': group_names})
    except Exception as e:
        print(f"Error fetching groups from database: {e}")
    
    # Fallback to default groups
    return jsonify({
        'data': ['Little Angels', 'Saints', 'Disciples', 'Trendsetters']
    })

@app.route('/api/groups/<group_name>', methods=['PUT'])
@require_auth
def update_group(group_name):
    """Update group (e.g., assign teacher)"""
    from utils.db_helpers import get_group_by_name
    
    try:
        data = request.get_json()
        group = get_group_by_name(group_name)
        
        if not group:
            return jsonify({'error': 'Group not found'}), 404
        
        if 'teacher_id' in data:
            group.teacher_id = data['teacher_id'] if data['teacher_id'] else None
            try:
                from database import db
                db.session.commit()
            except:
                pass
        
        return jsonify({'data': group.to_dict()})
    except Exception as e:
        print(f"Error updating group: {e}")
        try:
            from database import db
            db.session.rollback()
        except:
            pass
        return jsonify({'error': 'Failed to update group'}), 500

# ============================================================================
# USERS ENDPOINTS
# ============================================================================

@app.route('/api/users', methods=['GET'])
@require_auth
def list_users():
    """List users, optionally filtered by role"""
    from utils.db_helpers import get_users_by_role
    
    role = request.args.get('role')
    
    try:
        if role:
            users = get_users_by_role(role)
        else:
            try:
                from models import User
                if User:
                    users = User.query.all()
                else:
                    users = []
            except:
                users = []
        
        return jsonify({
            'data': [u.to_dict() for u in users] if users else []
        })
    except Exception as e:
        print(f"Error fetching users: {e}")
        return jsonify({'data': []})

@app.route('/api/users', methods=['POST'])
@require_auth
def create_user():
    """Create new user and send invitation"""
    data = request.get_json()
    email = data.get('email', '').lower()
    name = data.get('name', '')
    role = data.get('role', '').title()
    
    # Generate temporary password/token for invitation
    import secrets
    invitation_token = secrets.token_urlsafe(32)
    
    user_id = f"{role.lower()}_{len(users_db) + 1}"
    user = {
        'id': user_id,
        'email': email,
        'name': name,
        'role': role.lower(),
        'status': 'pending',
        'invitation_token': invitation_token,
        'invitation_sent_at': datetime.now().isoformat()
    }
    users_db[user_id] = user
    
    # In production, send email invitation here
    print(f"📧 Invitation sent to {email} with token: {invitation_token}")
    
    return jsonify({'data': user}), 201

@app.route('/api/users/resend-invitation', methods=['POST'])
@require_auth
def resend_invitation():
    """Resend invitation to user"""
    data = request.get_json()
    email = data.get('email', '').lower()
    
    # Find user by email
    user = None
    for u in users_db.values():
        if u.get('email') == email:
            user = u
            break
    
    if not user:
        return jsonify({'error': 'User not found'}), 404
    
    # Generate new invitation token
    import secrets
    invitation_token = secrets.token_urlsafe(32)
    user['invitation_token'] = invitation_token
    user['invitation_sent_at'] = datetime.now().isoformat()
    
    # In production, send email invitation here
    print(f"📧 Invitation resent to {email} with token: {invitation_token}")
    
    return jsonify({'data': {'message': 'Invitation resent successfully'}})

# ============================================================================
# HEALTH CHECK
# ============================================================================

@app.route('/api/health', methods=['GET'])
def health():
    """Health check endpoint"""
    from utils.db_helpers import test_db_connection
    
    db_status = 'connected' if test_db_connection() else 'disconnected'
    
    return jsonify({
        'status': 'ok',
        'database': db_status,
        'timestamp': datetime.now().isoformat()
    })

# ============================================================================
# ERROR HANDLERS
# ============================================================================

@app.errorhandler(404)
def not_found(error):
    return jsonify({'error': 'Not found'}), 404

@app.errorhandler(500)
def internal_error(error):
    return jsonify({'error': 'Internal server error'}), 500

# ============================================================================
# RUN APPLICATION
# ============================================================================

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)

# RUN APPLICATION
# ============================================================================

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)
